import type { Metadata } from "next";
import "./globals.css";
import { Inter, Shantell_Sans } from "next/font/google"; // Import the cursive font
import { NavbarDemo } from "@/components/Navbar";


const inter = Inter({ subsets: ['latin'] });
const shantellSans = Shantell_Sans({ subsets: ['latin'] }); // Add Shantell Sans


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${shantellSans.className} antialiased`}
      >
     
            <NavbarDemo/>
            {children}
   
        
      </body>
    </html>
  );
}
